### PR TITLE
ENH: Customized VSCode Window Color

### PR DESCRIPTION
**Pull request by ant0nsc**
Title and activity bar red

### CODE REVIEW

**Review by fepegar — COMMENTED** [review]
What is the purpose of this?

**Comment by ant0nsc** [comment]
@fepegar , it's relating to a discussion on Teams where I was saying that multiple VSCode windows for different repos are confusing, and it's easier to keep them apart if colored.

**Comment by fepegar** [comment]
I see. Interesting! Can you please share a screenshot?

**Comment by ant0nsc** [comment]
@fepegar , below is an example. Most importantly, the window colors are clearly visible in the window preview in the taskbar:

**Review by fepegar — APPROVED** [review]
Nice, thanks!

**Review by fepegar — CHANGES_REQUESTED** [review]
Do you think blue would make more sense than red? As red is typically used for errors.

**Review by fepegar — APPROVED** [review]

**Review by mebristo — APPROVED** [review]

**Review by fepegar — APPROVED** [review]

**Review by javier-alvarez — APPROVED** [review]

**Pull request merged**
