### PR TITLE
Deprecate manual changelog

### PR DESCRIPTION
**Pull request by fepegar**
This replicates what we did for `hi-ml`:
- https://github.com/microsoft/hi-ml/pull/216

### CODE REVIEW

**Review by ant0nsc — DISMISSED** [review]

**Comment by fepegar** [comment]
Something happened with `nbconvert` in the Hello World test. @mebristo could you please verify that it's not our fault?

**Comment by fepegar** [comment]
Waiting for https://github.com/microsoft/hi-ml/pull/265 to be merged.

**Comment by ant0nsc** [comment]
@fepegar, hi-ml has just been updated, can you add the latest main in the submodule?

**Comment by fepegar** [comment]
Waiting for #709 to be merged.

**Comment by ant0nsc** [comment]
@fepegar , I think we should then also add a build step that checks if the title matches the expected rules, like we did in hi-ml in https://github.com/microsoft/hi-ml/pull/224? Were you planning to do that in a separate PR?

**Comment by fepegar** [comment]
> @fepegar , I think we should then also add a build step that checks if the title matches the expected rules, like we did in hi-ml in https://github.com/microsoft/hi-ml/pull/224? Were you planning to do that in a separate PR?

I think that's a good idea. Yes, I think we can add that after this has been merged, but I'm happy to add it here if you think it's easier.

**Review by javier-alvarez — APPROVED** [review]

**Review by mebristo — APPROVED** [review]

**Pull request merged**
